spring.application.name=gym-tobifit
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gym_tobyfit}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
